
### 1.1 Creating a Vector

In [3]:
# load library
import numpy as np

# create a vector as a row
vector_row = np.array([1, 2, 3])

# create a vetor as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

### 1.2 Creating a Matrix


In [4]:
# load library
import numpy as np

# create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

#### Discussion
To create a matrix we can use a NumPy two-dimensional array. In our solution, the matrix contains three rows and two columns (a column of 1s and a column of 2s)

NumPy actually has a dedicated matrix data structure:

In [10]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])

### 1.3 Creating a Sparse Matrix
#### Problem
Given data with very few nonzero values, you want to efficiently represent it.

#### Solution
Create a sparse matrix:

In [6]:
# load libraries
import numpy as np
from scipy import sparse

# create a matrix
matrix = np.array([[0, 0],
                  [0, 1],
                  [3, 0]])

# create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [7]:
# view sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


There are a number of types of sparse matrices. However, in compressed sparse row (CSR) matrices, (1, 1) and (2, 0) represent the (zero-indexed) indices of the non-zero values 1 and 3, respectively. For example, the element 1 is in the second row and second column. We can see the advantage of sparse matrices if we create a much larger matrix with many more zero elements and then compare this larger matrix with our original sparse matrix:

In [9]:
# create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

# view original sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [10]:
# view larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


As we can see, despite the fact that we added many more zero elements in the larger matrix, its sparse representation is exactly the same as our original sparse matrix. That is, the addition of zero elements did not change the size of the sparse matrix.

### 1.4 Selected Elements
#### Problem
You need to select one or more elements in a vector or matrix.

#### Solution
NumPy's arrays make that easy

In [14]:
# load library
import numpy as np

# create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# select the third element of vector
vector[2]

3

In [15]:
# select second row, second column
matrix[1,1]

5

In [16]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [18]:
# select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [19]:
# select the last element
vector[-1]

6

In [20]:
# select the first two rows and all columns of a matrix
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

### 1.5 Describing a Matrix
#### Problem
You want to describe the shape, size, and dimensions of the matrix

#### Solution
Use shape, size, and ndim:

In [24]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# view number of rows and columns
matrix.shape

(3, 4)

In [25]:
# view number of elements (rows * columns)
matrix.size

12

In [26]:
# view number of dimensions
matrix.ndim

2

### 1.6 Applying Operations to Elements
#### Problem
You want to apply some function to multiple elements in an array.

#### Solutions
Use NumPy's vectorize:

In [27]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# create function that adds 1000 to something
add_1000 = lambda i: i + 1000

# create vectorized function
vectorized_add_1000 = np.vectorize(add_1000)

# apply function to all elementsin matrix
vectorized_add_1000(matrix)

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

In [28]:
# add 1000 to all elements
matrix + 1000

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

### Finding Maximum and Minimum Values
#### Problem
You need to find the maximum or minimum value in an array.

#### Solution
Use NumPy's max and min:

In [29]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# rreturn maximum element
np.max(matrix)

9

In [30]:
# return minimum element
np.min(matrix)

1

In [31]:
# find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [32]:
# find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

### 1.8 Calculating the Average, Variance, and Standard Deviation

#### Problem
You want to calculate some descriptive statistics about an array.

#### Solution
Use NumPy's mean, var, and std:

In [33]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# return mean
np.mean(matrix)

5.0

In [34]:
# return variance
np.var(matrix)

6.666666666666667

In [35]:
# return standard deviation
np.std(matrix)

2.581988897471611

In [36]:
# find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

### 1.9 Reshaping Arrays
#### Problem
You want to change the shape (number of rows and columns) of an array without changing the element values.

#### Solution
Use NumPy's reshape:

In [37]:
# load library
import numpy as np

# create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [38]:
matrix.size

12

One useful argument in reshape is -1, which effectively means “as many as needed,” so reshape(-1, 1) means one row and as many columns as needed:

In [39]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Finally, if we provide one integer, reshape will return a 1D array of that length:

In [40]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 1.10 Transposing a Vector or Matrix
#### Problem
You need to transpose a vector or matrix

#### Solution
Use the T method:

In [41]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Transposing is a common operation in linear algebra where the column and row indices of each element are swapped. One nuanced point that is typically overlooked outside of a linear algebra class is that, technically, a vector cannot be transposed because it is just a collection of values:

In [42]:
# transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

However, it is common to refer to transposing a vector as converting a row vector to a column vector (notice the second pair of brackets) or vice versa:

In [43]:
# transpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### 1.11 Flattening a Matrix
#### Problem
You need to transform a matrix into a one-dimensional array.

#### Solution
Use flatten:

In [44]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Discussion
flatten is a simple method to transform a matrix into a one-dimensional array. Alternatively, we can use reshape to create a row vector:

In [45]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 1.12 Finding the Rank of a Matrix
#### Problem
You need to know the rank of a matrix

#### Solution
Use NumPy's linear algebra method matrix_rank:

In [46]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# return matrix rank
np.linalg.matrix_rank(matrix)

2

### 1.13 Calculating the Determinant
#### Problem
You need to know the determinant of a matrix

#### Solution
Use NumPy's linear algebra method det:

In [48]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# return the determinant of matrix
np.linalg.det(matrix)

0.0

In [49]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# return diagonal elements
matrix.diagonal()

array([1, 4, 9])

#### Discussion
NumPy makes getting the diagonal elements of a matrix easy with diagonal. It is also possible to get a diagonal off from the main diagonal by using the offset parameter:

In [50]:
# return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [52]:
# return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])

### 1.15 Calculating the Trace of a Matrix
#### Problem
You need to calculate the trace of a matrix

#### Solution
Use trace:

In [53]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# return trace
matrix.trace()

14

In [54]:
# return diagonal and sum elements
sum(matrix.diagonal())

14

### 1.16 Finding Eigenvalues and Eigenvectors
#### Problem
You need to find the eigenvalues and eigenvectors of a square matrix.

#### Solution
Use NumPy's linalg.eig:

In [56]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

# calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# view eigenvalues
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [57]:
# view eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

In [60]:
# load library
import numpy as np

# create two vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# calculate dot product
np.dot(vector_a, vector_b)

32

In [61]:
# calculate dot product
vector_a @ vector_b

32


### 1.18 Adding and Subtracting Matricies
#### Problem
You want to add or subtract two matricies

#### Solution
Use NumPy's add and subtract:

In [76]:
# load library
import numpy as np

# create matricies
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# add two matricies
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [77]:
# subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

#### Discussion
Alternatively, we can simply use the + and - operators:

In [78]:
# add two matricies
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

### 1.19 Multiplying Matricies
#### Problem
You want to multiply two matrices.

#### Solution
Use NumPy's dot:

In [79]:
# load library
import numpy as np

# create matrices
matrix_a = np.array([[1, 1],
                     [1, 2]])

matrix_b = np.array([[1, 3],
                     [1, 2]])

# multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

#### Discussion
Alternatively, in Python 3.5+ we can use the @ operator:

In [80]:
# multiply two matrices
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

### 1.20 Inverting a Matrix
#### Problem
You want to calculate the inverse of a square matrix.

#### Solution
Use NumPy's linear algebra inv method:

In [64]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 4],
                  [2, 5]])

# calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [65]:
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

### 1.21 Generating Random Values
#### Problem
You want to generate pseudorandom values.

#### Solution
Use NumPy's random:

In [69]:
# load library
import numpy as np

# set seed
np.random.seed(0)

# generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [70]:
# genereate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

Alternatively, we can generate numbers by drawing them from a distribution:

In [71]:
# draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [73]:
# draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [75]:
# draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])